FROM php:8.5-apache


RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev \
    unzip \
    curl \
    git \
    && docker-php-ext-install pdo_pgsql mbstring exif pcntl bcmath gd zip

RUN a2enmod rewrite


WORKDIR /var/www/html


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . /var/www/html


ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf



RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs


RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80